# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=40, null=True, verbose_name='Name')),
                ('contact_email', models.EmailField(max_length=40, null=True, verbose_name='Email')),
                ('remember', models.BooleanField(default=True, verbose_name='Receive email updates')),
                ('content', models.CharField(max_length=40, null=True, verbose_name='Say stuff')),
            ],
        ),
    ]
