# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='content',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='remember',
        ),
    ]
